### ISSUE TITLE
Enabling JMX Monitoring Results in Duplicate Labels

### ISSUE THREAD

**Issue by trexx** [Xtigyro/puppetserver-helm-chart#237]
## Describe the Bug

The configmap for the JMX configuration contains duplicate labels.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-puppetserver-jmx-config
  labels:
    app.kubernetes.io/component: puppetserver
    app.kubernetes.io/name: puppetserver
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: puppetserver-9.5.2
    app.kubernetes.io/version: 7.17.0
    app.kubernetes.io/component: puppetserver-compilers
    app.kubernetes.io/name: puppetserver
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: puppetserver-9.5.2
    app.kubernetes.io/version: 7.17.0
```

This causes helm / argocd to barf.

## Expected Behavior (_Behaviour_)

No duplicate labels.

## Steps to Reproduce
Steps to reproduce the behavior (_Behaviour_): 

```
  metrics:
    prometheus:
      disableAPICheck: true
      puppetdb:
        enabled: true
      jmx:
        enabled: true
```

Its likely its unnecessary we have the compiler labels and it maybe possible to have them removed.
